[project]
name = "epub-to-markdown"
version = "0.1.0"
description = "Converts an EPUB file to GFM Markdown with advanced processing."
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = []
